---
title: "Přerov čtverce"
format: 
  html:
    code-fold: true
editor: visual
---

## Faunistické čtverce pro Přerov {#sec-about}

Černá = katastr Přerov.

Červená = detailní čtverce.

Modrá = malé faunistické čtverce, kliknutím se zobrazí číslo.

```{r echo = FALSE, message = FALSE, error = FALSE, warning = FALSE, result = 'hide', fig.keep = 'all'}
#| code-fold: true
#| code-summary: "Show the code"
#| 
library(leaflet)
library(sf)
library(RCzechia)
library(tidyverse)

# katastr Prerov
Prerov <- RCzechia::obce_polygony() %>%
  filter(NAZ_OBEC == "Přerov")

# faunisticke ctverce (male = cislo s pismenem)
sq.Prerov.high <- st_join(KFME_grid("high"), Prerov, left = F)

# extra detailni deleni ctvercu 
sq.Prerov.aaaa <- st_make_grid(sq.Prerov.high, n = c(24, 24))

# interaktivni mapa
# seda = katastr Prerov
# cervena = detailni ctverce
# modra = male faunisticke ctverce, kliknutim se zobrazi cislo
leaflet(data = republika("low")) %>% 
  addProviderTiles("CartoDB.Positron") %>% 
  addPolygons(data = Prerov, color = "black", weight = 1, fillOpacity = 0) %>% 
  addPolygons(data = sq.Prerov.aaaa, color = "red", weight = 1, fillOpacity = 0) %>% 
  addPolygons(data = sq.Prerov.high, color = "blue", weight = 1, fillOpacity = 0, popup = ~as.character(ctverec)) %>%
  leaflet.extras::addResetMapButton()
```

34 čtverců, které zasahují na katastr Přerova z více než 30 %.

1 čtverec = 4 předchozí detailní čtverce.

```{r echo = FALSE, message = FALSE, error = FALSE, warning = FALSE, result = 'hide', fig.keep = 'all'}
sq.Prerov.aaa <- st_make_grid(sq.Prerov.high, n = c(12, 12))

d <- data.frame(ID = 1:length(sq.Prerov.aaa), Overlap = 0)

for(i in 1:length(sq.Prerov.aaa)) {
area <- st_area(st_intersection(sq.Prerov.aaa[i], Prerov)) / st_area(sq.Prerov.aaa[i]) * 100
  if(length(area) == 1) {d[i, ]$Overlap <- area}
}

leaflet(data = republika("low")) %>% 
  addProviderTiles("CartoDB.Positron") %>% 
  addPolygons(data = Prerov, color = "black", weight = 1, fillOpacity = 0) %>% 
  addPolygons(data = sq.Prerov.aaa[subset(d, Overlap >= 30)$ID], color = "red", weight = 1, fillOpacity = 0) %>% 
  leaflet.extras::addResetMapButton()
```
